# Site settings
title: Pyronear
description: "D√©tection pr√©coce de feux de for√™t" # this means to ignore newlines until "baseurl:"
author: Pyronear
url: "https://pyronear.org/" # the base hostname & protocol for your site
lang: fr 
languages: ["fr", "en"]
base-url: ""

# Social media
twitter: # Card customization
  username: pyro_near
  card: summary

social:
  links:
    - https://twitter.com/pyro_near
    - https://www.facebook.com/pyronear
    - https://www.linkedin.com/company/37560523
    - https://github.com/pyronear


twitter_username: pyro_near
facebook_username: pyronear
linkedin_username: pyronearfr
github_username: pyronear

logo: /img/logo.png
logo_full: /img/logo_letters.png
locale: fr_FR

#¬†SEO
google_site_verification: NRZ27lDopfjKH3Lx1eWvh6WczAGh0hgqVg0AtB-ZK6c
google_analytics: UA-179976746-1


# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Translations
t:
  fr:
    label: fr
    icon: üá´üá∑
    description: "D√©tection pr√©coce de feux de for√™t"
    buttons:
      moreInfo: "En savoir plus"
      contactUs: "Nous contacter"
      submit: "Envoyer"
    header:
      title: "D√©tection pr√©coce des d√©parts de feux"
      subtitle: "Pyronear est un projet open-source au service du bien commun"
    manifesto:
      title: "Qui sommes-nous ?"
      phrase1: "<b>Pyronear</b> est une association √† but non lucratif loi 1901 dont l‚Äôobjectif est de d√©mocratiser des solutions technologiques sobres et ouvertes de lutte contre les incendies de for√™ts, au service des √©cosyst√®mes et des citoyens. Pour cela, nous co-construisons une solution open source de d√©tection d√©tection pr√©coce, performante, automatique, √©nergiquement sobre, √©conomique et modulable des d√©parts de feux dans les espaces naturels."
      phrase2: "<b>Open source </b>: Tout notre code est disponible en acc√®s libre et co-d√©velopp√© par nos b√©n√©voles. Nous pensons que l'intelligence collective est la meilleure fa√ßon de r√©soudre un probl√®me complexe."
      phrase3: "<b>D√©tection pr√©coce </b>: Pour lutter efficacement contre les feux de for√™t il est important de les d√©tecter de fa√ßon pr√©coce pour permettre une intervention rapide des services d‚Äôincendies et secours et ainsi limiter leur impact."
      phrase4: "<b>Performance </b>: Nos experts en intelligence artificielle suivent activement l‚Äôactualit√© de ce domaine en plein √©bullition afin de faire b√©n√©ficier Pyronear de ses derni√®res avanc√©es."
      phrase5: "<b>Automatique </b>: Nous proposons une solution compl√®tement automatis√©e afin de lib√©rer du temps aux pompiers."
      phrase6: "<b>√ânerg√©tiquement sobre </b>: Nous sommes dans une d√©marche dite low-tech, nous avons construit un dispositif peu consommateur permettant un d√©ploiement plus facile et une utilisation plus raisonn√©e de nos pr√©cieuses ressources."
      phrase7: "<b>√âconomique </b>: Notre R&D est faite par des b√©n√©voles, notre dispositif est sobre et l‚Äôobjet non-lucratif de notre association, ce qui nous permet de proposer des prix tr√®s comp√©titifs afin de faciliter un d√©ploiement sur le territoire."
      phrase8: "<b>Modulable </b>: Nous proposons un syst√®me de d√©tection complet mais notre dispositif a √©t√© pens√© pour fonctionner avec le mat√©riel existant (utilisation de cam√©ras d√©j√† en place, connexion avec nexSIS ‚Ä¶)"
    steps:
      title: "Comment √ßa marche ?"
      text1: "Pyronear est une <b>solution compl√®te de gestion du risque incendie</b>. Elle est constitu√©e d‚Äôun <b>algorithme de d√©tection</b> pr√©coce des d√©parts de feu, impl√©ment√© sur un micro ordinateur, connect√© √† des <b>cam√©ras positionn√©es sur des points hauts</b> avec vue sur la for√™t. Nos d√©tecteurs communiquent les <b>alertes de d√©tection de d√©part de feu</b> √† une base de donn√©es elle-m√™me connect√©e √† une <b>plateforme de supervision</b> √† destination des pompiers. "
      image_link1: "https://lh3.googleusercontent.com/drive-viewer/AFGJ81ray0VxVjHBRwWV2U3UW9rNMlw8QZBNqOsNdGN8Pq2-FHWgjYt3uQpqO0aHpyxTdWViy7q50tNbpy9HZ-14oxuNSbft=s1600"
      text2: "Nos tours de d√©tection se composent de 4/5 cam√©ras haute r√©solution et d‚Äôun micro ordinateur qui capture une image par cam√©ra √† intervalles r√©guliers puis l‚Äôanalyse localement √† l‚Äôaide de notre mod√®le de d√©tection de feux de for√™t. En cas de d√©tection, le mode alerte est activ√©, toutes les images provenant de la cam√©ra ayant d√©tect√© le feu sont alors envoy√©es √† notre base de donn√©es via notre api, le protocole de communication que nous avons d√©velopp√©."
      image_link2: "https://lh3.googleusercontent.com/drive-viewer/AFGJ81rKFDSwOWe1s6g0nANvlaKnbAMsCqNy4cLncnazqA_uKR928VWIgks5ds5htWhuZq_RfA41pgllkhDNUm3Yq-hDyMMd=s1600"

    callToAction:
      title: "Comment le mettre en place ?"
      content: "Pour en savoir plus envoyez-nous un mail ou contactez-nous sur les r√©seaux sociaux. Nous vous r√©pondrons le plus rapidement possible."
    team:
      title: "L'√©quipe actuelle"
    sponsors:
      title: "Qui nous soutient ?"
      sponsor1:
        title: "Data for Good"
        url: "https://dataforgood.fr/"
        logo: "https://dataforgood.fr/img/logo-dfg-new2.png"
        content: "Membre de la saison 6, 8 et 10 de Data for Good, c'est l√† que Pyronear a vu le jour parmi de nombreux projets d'int√©r√™t g√©n√©ral."
      sponsor2:
        title: "Atraksis"
        url: "https://atraksis.fr/"
        logo: "https://atraksis.fr/wp-content/themes/atraksis/assets/img/logo-atraksis-footer.svg"
        content: "Acteur de l'innovation pour les secours, c'est notre point de contact avec les pompiers."
      sponsor3:
        title: "SDIS Ard√®che"
        url: "https://www.sdis07.fr/"
        logo: "https://www.sdis07.fr/ardeche-secours-incendie/themes/sapeurs-pompiers-ardeche/medias/img/logo-sdis07-pompiers-ardeche.png"
        content: "Notre partenaire pour le recueil des besoins et l'exp√©rimentation terrain."
    contactForm:
      title: "Prot√©geons nos for√™ts"
      email:
        label: "Votre adresse e-mail"
        privacyPhrase: "Nous ne partagerons jamais votre adresse e-mail sans votre autorisation."
      subject:
        label: "Objet"
      message:
        label: "Votre message"
      confirmation:
        title: "Message envoy√© !"
        subtitle: "Merci de nous avoir contact√©, nous revenons vers vous le plus vite possible !"
    contact:
      title: "Suivez l'aventure Pyronear"
      content: "Pour se tenir inform√© de l'avancement du projet ou rejoindre l'aventure, retrouvez-nous sur les r√©seaux sociaux !"
  en:
    label: en
    icon: üá¨üáß
    description: "Early detection of forest wildfires"
    buttons:
      moreInfo: "More information"
      contactUs: "Contact us"
      submit: "Submit"
    header:
      title: "Early detection of wildfires"
      subtitle: "Pyronear is an open-source project for the common good"
    manifesto:
      title: "Who are we?"
      phrase1: "<b>Pyronear</b> is a non-profit NGO whose objective is to democratize open and low-tech solutions for fighting wildfires, for the benefit of the ecosystems and the citizens. To achieve this goal, we are co-building an early detection solution that is open source, efficient, automatic, energy-efficient, economical and modular"
      phrase2: "<b>Open source</b>: All our code is available for free and co-developed by our volunteers. We believe that collective intelligence is the best way to solve a complex problem."
      phrase3: "<b>Early detection</b>: To fight effectively against wildfires, it is important to detect them early in order to allow a quick intervention of fire and rescue services and thus limit their impact."
      phrase4: "<b>Performance</b>: Our AI experts actively follow the news in this fast-moving field in order to make Pyronear benefit from its latest advances."
      phrase5: "<b>Automatic</b>: We offer a fully automated solution to free up firefighters' time."
      phrase6: "<b>Energetically sober</b>: We are in a so-called low-tech approach, we have built a low-consumption device allowing an easier deployment and a more reasoned use of our precious resources."
      phrase7: "<b>Economic</b>: Our R&D is done by volunteers, our device is sober and the non-profit object of our association, which allows us to propose very competitive prices to facilitate a deployment on the territory."
      phrase8: "<b>Modular</b>: We offer a complete detection system but our device has been designed to work with existing equipment (use of cameras already in place, connection with existing software ...)"
    steps:
      title: "Comment √ßa marche ?"
      text1: "Pyronear is a <b>complete fire risk management solution</b>. It consists of an <b>early wildfire detection algorithm</b>, implemented on a microcomputer, connected to <b>cameras positioned on high spots</b> with a view on the forest. Our detectors communicate <b>fire alerts<b> to a database that is connected to a <b>supervision platform</b> for the fire department."
      image_link1: "https://lh3.googleusercontent.com/drive-viewer/AFGJ81ray0VxVjHBRwWV2U3UW9rNMlw8QZBNqOsNdGN8Pq2-FHWgjYt3uQpqO0aHpyxTdWViy7q50tNbpy9HZ-14oxuNSbft=s1600"
      text2: "Our detection towers consist of 4/5 high resolution cameras and a micro computer. We capture one image per camera at regular intervals and then analyze it locally using our wildfire detection model. In case of detection, the alert mode is activated, all the images coming from the camera having detected the fire are then sent to our database via our api, the communication protocol we have developed."
      image_link2: "https://lh3.googleusercontent.com/drive-viewer/AFGJ81rKFDSwOWe1s6g0nANvlaKnbAMsCqNy4cLncnazqA_uKR928VWIgks5ds5htWhuZq_RfA41pgllkhDNUm3Yq-hDyMMd=s1600"

    callToAction:
      title: "How to deploy it?"
      content: "To get more information, reach us by email or on social networks. We will get back to you as soon as possible."
    team:
      title: "The current team"
    sponsors:
      title: "Who supports us?"
      sponsor1:
        title: "Data for Good"
        url: "https://dataforgood.fr/"
        logo: "https://dataforgood.fr/img/logo-dfg-new2.png"
        content: "Part of the 6th, 8th and 10th acceleration seasons of Data for Good, it is the birth place of Pyronear among many other common good projects."
      sponsor2:
        title: "Atraksis"
        url: "https://atraksis.fr/"
        logo: "https://atraksis.fr/wp-content/themes/atraksis/assets/img/logo-atraksis-footer.svg"
        content: "A stakeholder for rescue innovation, and our point of contact with firefighters."
      sponsor3:
        title: "SDIS Ard√®che"
        url: "https://www.sdis07.fr/"
        logo: "https://www.sdis07.fr/ardeche-secours-incendie/themes/sapeurs-pompiers-ardeche/medias/img/logo-sdis07-pompiers-ardeche.png"
        content: "Our partner for requirements gathering and field experimentation."
    contactForm:
      title: "Let us protect our forests"
      email:
        label: "Your e-mail address"
        privacyPhrase: "We will never share your email without your consent."
      message:
        label: "Your message"
      confirmation:
        title: "Message sent!"
        subtitle: "Thank you for contacting us, we will get back to you as soon as possible!"
    contact:
      title: "Follow the Pyronear adventure"
      content: "To stay updated about our progress or to join the adventure, you can also reach us on social media!"
