# Site settings
title: Pyronear
description: "Détection précoce de feux de forêt" # this means to ignore newlines until "baseurl:"
baseurl: "https://pyronear.github.io/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Social media
twitter_username: pyro_near
facebook_username: pyronear
linkedin_username: pyronearfr
github_username: pyronear

# SEO
google_analytics: UA-179976746-1

# Build settings
markdown: kramdown

# Traduction
t:
  fr:
    buttons:
      moreInfo: "En savoir plus"
      contactUs: "Nous contacter"
      submit: "Envoyer"
    header:
      title: "Détection précoce des départs de feux"
      subtitle: "Pyronear est un projet open-source au service du bien commun"
    manifesto:
      title: "Qui sommes-nous ?"
      phrase1: "Pyronear est une association loi 1901 au service du bien commun et du logiciel libre."
      phrase2: "Nous portons la conviction que la protection des forêts doit être accessible à tous et qu'elle nécessite la technologie la plus efficace, transparente et abordable possible. C’est pourquoi notre solution logicielle de détection des feux de forêt est gratuite."
    steps:
      title: "Comment ça marche ?"
      step1:
        title: "1. Couverture de la zone"
        content: "Nos détecteurs placés en hauteur surveillent la zone forestière alentour."
      step2:
        title: "2. Traitement de l'image"
        content: "Notre modèle d'apprentissage profond analyse les indices visuels de départ de feu."
      step3:
        title: "3. Alerte !"
        content: "En cas de forte suspicion, l'alerte est donnée automatiquement."
    callToAction:
      title: "Comment le mettre en place ?"
      content: "Pour en savoir plus envoyez-nous un mail ou contactez-nous sur les réseaux sociaux. Nous vous répondrons le plus rapidement possible."
    team:
      title: "L'équipe actuelle"
    sponsors:
      title: "Qui nous soutient ?"
      sponsor1:
        title: "Data for Good"
        content: "Membre de la saison 6 et 8 de Data for Good, c'est là que Pyronear a vu le jour parmi de nombreux projets d'intérêt général."
      sponsor2:
        title: "Atraksis"
        content: "Notre partenaire pour les phases de test sur le terrain, et notre intermédiaire avec les pompiers."
    contactForm:
      title: "Protégeons nos forêts"
      email:
        label: "Votre adresse e-mail"
        privacyPhrase: "Nous ne partagerons jamais votre adresse e-mail sans votre autorisation."
      message:
        label: "Votre message"
      confirmation:
        title: "Message envoyé !"
        subtitle: "Merci de nous avoir contacté, nous revenons vers vous le plus vite possible !"
    contact:
      title: "Suivez l'aventure Pyronear"
      content: "Pour se tenir informé de l'avancement du projet ou rejoindre l'aventure, retrouvez-nous sur les réseaux sociaux !"
  en:
    buttons:
      moreInfo: "More information"
      contactUs: "Contact us"
      submit: "Submit"
    header:
      title: "Early detection of wildfires"
      subtitle: "Pyronear is an open-source project for the common good"
    manifesto:
      title: "Who are we?"
      phrase1: "Pyronear is a French association (loi 1901) at the service of the common good and open-source software."
      phrase2: "We believe that forest preservation should be accessible to anyone and that it requires the most efficient, transparent and affordable technology possible. That is why our software solution for wildfire detection is free of charge."
    steps:
      title: "How does it work?"
      step1:
        title: "1. Area surveillance"
        content: "Our detectors places on high vantage points watch over the nearby forest area."
      step2:
        title: "2. Image processing"
        content: "Our deep learning model analyzes visual hints for wildfires."
      step3:
        title: "3. Alert!"
        content: "In case of important suspicions, the alert is raised automatically."
    callToAction:
      title: "How to deploy it?"
      content: "To get more information, reach us by email or on social networks. We will get back to you as soon as possible."
    team:
      title: "The current team"
    sponsors:
      title: "Who supports us?"
      sponsor1:
        title: "Data for Good"
        content: "Part of the 6th and 8th acceleration season of Data for Good, it is the birth place of Pyronear among many other common good projects."
      sponsor2:
        title: "Atraksis"
        content: "Our partner for field testing phases, and our intermediary with firefighters."
    contactForm:
      title: "Let us protect our forests"
      email:
        label: "Your e-mail address"
        privacyPhrase: "We will never share your email without your consent."
      message:
        label: "Your message"
      confirmation:
        title: "Message sent!"
        subtitle: "Thank you for contacting us, we will get back to you as soon as possible!"
    contact:
      title: "Follow the Pyronear adventure"
      content: "To stay updated about our progress or to join the adventure, you can also reach us on social media!"
