# Site settings
title: Pyronear
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/pyronear.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: "pyronear"

# Build settings
markdown: kramdown

# Traduction
t:
  fr:
    buttons:
      moreInfo: "En savoir plus"
      contactUs: "Nous contacter"
      submit: "Envoyer"
    header:
      title: "Détectez les feux de forêts au plus tôt"
      subtitle: "Pyronear est une technologie open-source au service du bien commun."
    manifesto:
      title: "Nous sommes Pyronear, une association loi 1901."
      phrase1: "Nous sommes des bénévoles au service du bien commun et du logiciel libre."
      phrase2: "Nous pensons que la protection des foret doit etre accessible a tous et qu'elle nécessite la technologie la plus efficace, transparente et abordable possible."
    steps:
      title: "Comment ça marche ?"
      step1:
        title: "1. Observation de la zone"
        content: "Nos détecteurs placés en hauteur photographient la zone forestière alentour."
      step2:
        title: "2. Analyse des photos"
        content: "Les photos sont triées et analysées par une intelligence artificielle."
      step3:
        title: "3. Alerte !"
        content: "En cas de fumée suspecte, l'alerte est donnée automatiquement."
    callToAction:
      title: "Combien ça coûte ? Comment le mettre en place ?"
      content: "Pour en savoir plus envoyez-nous un mail ou contactez-nous sur les reseaux. Nous vous répondrons le plus rapidement possible."
    team:
      title: "L'équipe actuelle"
    contactForm:
      title: "Protégez vos forêts !"
      email:
        label: "Votre adresse e-mail"
        privacyPhrase: "Nous ne partagerons jamais votre adresse e-mail sans votre autorisation."
      message:
        label: "Votre message"
      confirmation:
        title: "Message envoyé !"
        subtitle: "Merci de nous avoir contacté,nous revenons vers vous le plus vite possible !"
  es:
    buttons:
      moreInfo: "En savoir plus"
      contactUs: "Nous contacter"
      submit: "Envoyer"
    header:
      title: "Hola que tal"
      subtitle: "Une technologie open-source au service du bien commun."
    manifesto:
      title: "Nous sommes Pyronear, une association loi 1901."
      phrase1: "Nous sommes des bénévoles au service du bien commun et du logiciel libre."
      phrase2: "Nous pensons que la protection des foret doit etre accessible a tous et qu'elle nécessite la technologie la plus efficace, transparente et abordable possible."
    steps:
      title: "Comment ça marche ?"
      step1:
        title: "1. Observation de la zone"
        content: "Nos détecteurs placés en hauteur photographient la zone forestière alentour."
      step2:
        title: "2. Analyse des photos"
        content: "Les photos sont triées et analysées par une intelligence artificielle."
      step3:
        title: "3. Alerte !"
        content: "En cas de fumée suspecte, l'alerte est donnée automatiquement."
    callToAction:
      title: "Combien ça coûte ? Comment le mettre en place ?"
      content: "Pour en savoir plus envoyez-nous un mail ou contactez-nous sur les reseaux. Nous vous répondrons le plus rapidement possible."
    team:
      title: "L'équipe actuelle"
    contactForm:
      title: "Protégez vos forêts !"
      email:
        label: "Votre adresse e-mail"
        privacyPhrase: "Nous ne partagerons jamais votre adresse e-mail sans votre autorisation."
      message:
        label: "Votre message"
      confirmation:
        title: "Message envoyé !"
        subtitle: "Merci de nous avoir contacté,nous revenons vers vous le plus vite possible !"
